networks:
  proxy:
    external: false

services:

  web:
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        - WITHOUT_ASSETS=true
    image: custom_table_demo
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/dev"
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    networks:
      - proxy
    environment:
      RAILS_MAX_THREADS: 10
      EDITOR: nano
      WEB_CONCURRENCY: 0
      RAILS_LOG_TO_STDOUT: "true" 
      RAILS_ENV: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      #RAILS_ENV: production
      #RAILS_SERVE_STATIC_FILES: "true" # prod
    volumes:
      - ./:/custom_table_demo
